language: php
php:
 - 7.4
  
before_script:
 - composer install
      
script:
 - phpunit
 
cache:
 directories:
  - $HOME/.composer/cache
  - $HOME/.cache
  - build/cache
  
after_success:
  - travis_retry php vendor/bin/php-coveralls
  
notifications:
 email: 
  - deadly.info@gmail.com