language: php
php:
 - 7.4
  
before_script:
 - composer install
      
script:
 - mkdir -p build/logs
 - vendor/bin/phpunit tests --coverage-clover build/logs/clover.xml
 - wget https://scrutinizer-ci.com/ocular.phar
 - php ocular.phar code-coverage:upload  --format=php-clover build/logs/clover.xml
 
cache:
 directories:
  - $HOME/.composer/cache
  - $HOME/.cache
  - build/cache
  
after_success:
  - travis_retry php vendor/bin/php-coveralls